# Generated by Django 5.2.8 on 2025-12-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_address_line1_user_address_line2_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
