# Generated by Django 5.2.8 on 2025-12-09 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Bags', 'Bags'), ('Books', 'Books'), ('Documents', 'Documents'), ('Money', 'Money'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched'), ('claimed', 'Claimed'), ('unclaimed', 'Unclaimed'), ('returned', 'Returned'), ('disposed', 'Disposed')], default='unclaimed', max_length=20),
        ),
    ]
