# Generated by Django 5.2.8 on 2025-12-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_category_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='denominations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_money',
            field=models.BooleanField(default=False),
        ),
    ]
