# Generated by Django 5.2.8 on 2025-12-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_amount_item_denominations_item_is_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='denominations',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_money',
        ),
    ]
