# Generated by Django 5.2.8 on 2025-12-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_amount_remove_item_denominations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_lost_or_found',
        ),
        migrations.AddField(
            model_name='item',
            name='date_found',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date_lost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time_found',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time_lost_exact',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time_lost_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='time_lost_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Accessories', 'Accessories'), ('Bags', 'Bags'), ('Books', 'Books'), ('Documents', 'Documents'), ('Money', 'Money'), ('Living Things', 'Living Things'), ('Other', 'Other')], max_length=50),
        ),
    ]
