# Generated by Django 5.2.8 on 2025-12-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='identifying_marks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='when_lost',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='where_lost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
