# Generated by Django 5.2.8 on 2025-12-04 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_identifying_marks_claim_when_lost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='matched_lost_exists',
            field=models.BooleanField(default=False),
        ),
    ]
