# Generated by Django 5.2.8 on 2025-12-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claim_matched_lost_exists'),
        ('items', '0005_remove_item_date_lost_or_found_item_date_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='created_by_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='claim',
            name='matched_found_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_claims', to='items.item'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='message',
            field=models.TextField(blank=True, help_text='Explain why you believe this item belongs to you. (Optional for system claims)', null=True),
        ),
    ]
